"""empty message

Revision ID: 2ab516a670d6
Revises: ea1415cdb624
Create Date: 2018-04-21 21:07:59.161764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab516a670d6'
down_revision = 'ea1415cdb624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'address')
    # ### end Alembic commands ###
