"""empty message

Revision ID: 7312c9436ae8
Revises: a09a0560f9ed
Create Date: 2018-04-21 22:04:53.824766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7312c9436ae8'
down_revision = 'a09a0560f9ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('place', sa.Column('rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'rating')
    op.drop_column('place', 'image_url')
    # ### end Alembic commands ###
