"""empty message

Revision ID: 93543ddaf812
Revises: c10583b935d3
Create Date: 2018-04-21 22:09:42.611289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93543ddaf812'
down_revision = 'c10583b935d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'rating')
    # ### end Alembic commands ###
