"""empty message

Revision ID: c10583b935d3
Revises: 7312c9436ae8
Create Date: 2018-04-21 22:07:00.795904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10583b935d3'
down_revision = '7312c9436ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('rating', sa.Integer(), nullable=False, server_default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'rating')
    # ### end Alembic commands ###
