"""empty message

Revision ID: cb8cd9c6886e
Revises: 510187f7afd6
Create Date: 2018-04-21 21:09:36.918122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8cd9c6886e'
down_revision = '510187f7afd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'address')
    # ### end Alembic commands ###
