"""empty message

Revision ID: ea1415cdb624
Revises: e73c9b8f5514
Create Date: 2018-04-21 21:06:47.143774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1415cdb624'
down_revision = 'e73c9b8f5514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'address')
    # ### end Alembic commands ###
